### ISSUE TITLE
Unremovable console printing

### ISSUE THREAD

**Issue by kckern** [mitchallen/maze-generator#7]
When `require("@mitchallen/maze-generator")` is invoked in a script using node CLI, it prints two anonymous functions to the console.
```
[Function (anonymous)]
[Function (anonymous)]
```

This disrupts and clutters console output when CLI interaction or logging is important.

How can we suppress these logs? 

The culprit seems to be these nested functions:
https://github.com/mitchallen/maze-generator/blob/2080faf3b5d7b90cb3a09061ee0fbe39a6c30d94/dist/maze-generator.js#L1-L8

**Comment by mitchallen** [comment]
That references the distributed code.  I'd need more context.

**Comment by kckern** [comment]
I'm not sure where it is happening in the source, but every time I invoke `require("@mitchallen/maze-generator")` is prints this to the console: 
<img width="206" alt="image" src="https://user-images.githubusercontent.com/441229/191760515-98d79281-f038-4c29-a44f-5928312e1ca7.png">

That distributed code snippet is my best guess, but I really don't know, which is why I am asking.

Can you try to reproduce the issue?

**Comment by mitchallen** [comment]
If you can't provide better context or an example then all I can do is close this issue.

**Comment by kckern** [comment]
Here is an example:
```javascript
var mazeFactory = require("@mitchallen/maze-generator");
let xSize = 5;
let ySize = 6;
var maze = mazeFactory.Square({ x: xSize, y: ySize });
maze.generate();
maze.printBoard();
```
See the zip file.  Run it with `node runme.js`

This is the output:
<img width="324" alt="image" src="https://user-images.githubusercontent.com/441229/191777543-914af88b-4e3c-4073-b4bf-652c54cf7f04.png">

Why are those two functions being printed (in blue in the example above) to the console before the maze output?


[maze-issue-7.zip](https://github.com/mitchallen/maze-generator/files/9626852/maze-issue-7.zip)

**Comment by mitchallen** [comment]
I think I found the problem:

* https://github.com/mitchallen/grid/blob/master/src/index.js#L14

**Comment by mitchallen** [comment]
Fixed

**Comment by kckern** [comment]
Thank you kindly!  Works great now!
